### ISSUE TITLE
ספקות בנוגע לפרויקט

### ISSUE THREAD

**Issue by bargenish44** [orelrahum/Ransomware#1]
אשמח לקבל הסבר מפורט על איך אתה מתכנן לפתור את הבעיה הלא פתירה בזמן יעיל הזאת.

**Comment by orelrahum** [comment]
הכל פתיר.
גם p!=np,  רק עדיין לא הוכח.
מקווה שאוכיח לך אחרת

**Comment by bargenish44** [comment]
@orelrahum מחזיק לך אצבעות, בהצלחה!

**Comment by orelrahum** [comment]
בדוקטורט אוכיח p!=np .
מקווה שתמשיך לעקוב אחרייך.
בתודה, אוראל רחום
